#!/bin/sh

BOLD='\033[1;36m'
YELLOW_BOLD='\033[1;33m'
NC='\033[0m'
if command -v swiftformat &> /dev/null
then
    printf "${BOLD}[PRE-COMMIT]${NC} formatting code...\n"
    swiftformat . --exclude Pods
    git add -u
else
    printf "${YELLOW_BOLD}[WARNING]${NC} swiftformat is not installed. install it to automaitcally format code on commit\n"
fi
